### ISSUE TITLE
Event prefixes

### ISSUE THREAD

**Issue by richarddavenport** [AckerApple/ack-angular-webcam#11]
I'm going to start using this package, but the event names are killing my OCD. 
[https://angular.io/guide/styleguide#dont-prefix-output-properties](https://angular.io/guide/styleguide#dont-prefix-output-properties).
Can you deprecate the event names and align them with the angular style guide?
```
onSuccess => success
onError => error
```

Thanks for the package! Saving me lots of time!

**Comment by AckerApple** [comment]
This package, is a fork of this package: https://www.npmjs.com/package/ng2-webcam

I made a pull request and no one answered so I published my fork onto npm

I don't give too shats nor a rats tail about angular style guide, nor lints, but I'm all about pull requests.

You want what you want, do the work. You make the pull request.

Not offended, you just can't share your OCD with me and dangle a fish out there like "I'll still use this package". Cause I also don't give a donkey deek.

Enjoy the code

**Comment by richarddavenport** [comment]
Haha okay. Thanks @AckerApple, you made me laugh today!

**Comment by AckerApple** [comment]
Great, was hoping I wasn't too mouthy. I often get away with being sassy.

You might be interested in this. Here is my latest fork because someone let their package become outdated: https://www.npmjs.com/package/angular-file

It's a fork of this package: https://www.npmjs.com/package/ng2-file-upload

Jokes aside, consider a pull request. I enjoy working together and do think I have some cutting edge angular code.

Later good guy
