### ISSUE TITLE
Metadata version mismatch

### ISSUE THREAD

**Issue by avalero85** [AckerApple/ack-angular-webcam#25]
Hello! Congratulations for the plugin looks very good!

I am trying to install it to see it but it gives me the following error:

Metadata version mismatch for module [path] /node_modules/ack-angular-webcam/index.d.ts, found version 4, expected 3, resolving symbol AppModule in [path] /src/app/app.module.ts, resolving symbol AppModule in [path] /src/app/app.module.ts

Any idea? I just make an ng new and install your library.

Here is my package.json:

"dependencies": {
    "@ angular / animations": "^ 4.2.4",
    "@ angular / common": "^ 4.2.4",
    "@ angular / compiler": "^ 4.2.4",
    "@ angular / core": "^ 4.2.4",
    "@ angular / forms": "^ 4.2.4",
    "@ angular / http": "^ 4.2.4",
    "@ angular / platform-browser": "^ 4.2.4",
    "@ angular / platform-browser-dynamic": "^ 4.2.4",
    "@ angular / router": "^ 4.2.4",
    "core-js": "^ 2.4.1",
    "rxjs": "^ 5.4.2",
    "zone.js": "^ 0.8.14"
  },
  "devDependencies": {
    "@ angular / cli": "1.4.2",
    "@ angular / compiler-cli": "^ 4.2.4",
    "@ angular / language-service": "^ 4.2.4",
    "@ types / jasmine": "~ 2.5.53",
    "@ types / jasminewd2": "~ 2.0.2",
    "@ types / node": "~ 6.0.60",
    "ack-angular-webcam": "^ 1.7.1",
    "codelyzer": "~ 3.1.1",
    "jasmine-core": "~ 2.6.2",
    "jasmine-spec-reporter": "~ 4.1.0",
    "karma": "~ 1.7.0",
    "karma-chrome-launcher": "~ 2.1.1",
    "karma-cli": "~ 1.0.1",
    "karma-coverage-istanbul-reporter": "^ 1.2.1",
    "karma-jasmine": "~ 1.1.0",
    "karma-jasmine-html-reporter": "^ 0.2.2",
    "protractor": "~ 5.1.2",
    "ts-node": "~ 3.2.0",
    "tslint": "~ 5.3.2",
    "typescript": "~ 2.3.3"
  }

**Comment by AckerApple** [comment]
Hey! Thank you for the positive feedback as I have worked hard on this and other free packages.

I am most certain your issue is that you are on Angular4 and modules do not seem to "play nice" with Angular5 as documented in other sources and github issues to Angular. So, see if you cant get up to date and then try again... If you can't get on Angular5, then somewhere in my closed issue reports is a notation to the last commit that was for Angular4.

Lastly, please star, like, thumbs-up, favorite, OR whatever social actions you can do to help boost the popularity of this package.

Thank you in great kind. Close issue when satisfied.

**Comment by avalero85** [comment]
Yes! The problem was because I was not using Angular5 in my project. Now it works perfect.

Thank you very much for your time and for sharing your code.
