### ISSUE TITLE
Can't set camera component size

### ISSUE THREAD

**Issue by kk4fun** [AckerApple/ack-angular-webcam#30]
Hi.
When is use width & height parameters in options object there's no effect :(
Help pls :).

**Comment by AckerApple** [comment]
The width height seem to be working fine. I have updated the demo to include a width height toggle.

Try it out: https://ackerapple.github.io/ack-angular-webcam/

Look for "size" button

**Comment by kk4fun** [comment]
I solve this problem only throw in scss
```
**:host /deep/** {
        video {
            width: 500px;
            height: 400px;
        }
    }
```
I don't know why but width and height throw webcam options is not work for me. Closed now.

**Comment by AckerApple** [comment]
I wonder if its because you are using px ... try removing the "px"

**Comment by AckerApple** [comment]
Yeah, I looked up the width/height option type and its a number NOT string. Remove the px's

Type references can be found here:
https://github.com/AckerApple/ack-angular-webcam/blob/master/src/videoHelp.ts#L23

I think this is because the video element width/height attribute is being set INSTEAD of the video element's style attribute. As seen here:
https://github.com/AckerApple/ack-angular-webcam/blob/master/src/webcam.component.ts#L223

I think it would help you and others if the video.style.width was being set INSTEAD of video.width .... maybe?

I'd like for you to test if you would. Remove the px and let me know your results.
